"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronRight, CircleDot, Download, Feather, Library, LogOut, Menu, Minus, Pencil, Plus, Save, ScrollText, Share2, Swords, Trash2, Upload, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { toast, Toaster } from "sonner";
import { cacheCampaign, readCachedCampaigns, removeCachedCampaign, type CachedCampaign } from "@/lib/local-campaigns";

type Combatant = { id:string; name:string; kind:"player"|"monster"|"npc"; initiative:number; hp:number; maxHp:number; ac:number; conditions:string[]; monsterId?:string; campaignPlayerId?:string };
type CampaignPlayer = { id:string; name:string; hp:number|null; ac:number|null };
type Monster = { id:string; name:string; type:string; cr:string; ac:number; hp:number; speed:string; stats:string; abilities:string; spells:string; slots:number[] };
type SessionNote = { id:string; title:string; date:string; body:string; done:boolean };
type StoryBeat = { id:string; title:string; chapter:string; details:string; status:"planned"|"active"|"happened" };
type CampaignState = { campaignName:string; round:number; turn:number; combatants:Combatant[]; players:CampaignPlayer[]; monsters:Monster[]; sessions:SessionNote[]; story:StoryBeat[] };
type Campaign = CachedCampaign<CampaignState>;

const uid = () => Math.random().toString(36).slice(2,10);
const seed: CampaignState = {
  campaignName:"The Scale of Verdant Night", round:1, turn:0,
  combatants:[
    {id:"c1",name:"Lamfurion",kind:"player",initiative:18,hp:47,maxHp:52,ac:19,conditions:[]},
    {id:"c2",name:"Goblin Hexer",kind:"monster",initiative:15,hp:21,maxHp:32,ac:14,conditions:["Concentrating"],monsterId:"m1"},
    {id:"c3",name:"Ridgeback Drake",kind:"monster",initiative:11,hp:44,maxHp:58,ac:16,conditions:[],monsterId:"m2"},
  ],
  players:[],
  monsters:[
    {id:"m1",name:"Goblin Hexer",type:"Small humanoid",cr:"2",ac:14,hp:32,speed:"30 ft.",stats:"STR 8  DEX 16  CON 12  INT 14  WIS 11  CHA 15",abilities:"Nimble Escape — Disengage or Hide as a bonus action.\nHex Bolt — +5 to hit, 2d8 necrotic damage.",spells:"Cantrips: fire bolt, minor illusion\n1st: shield, witch bolt\n2nd: misty step",slots:[3,2,0,0,0]},
    {id:"m2",name:"Ridgeback Drake",type:"Medium dragon",cr:"3",ac:16,hp:58,speed:"40 ft., fly 60 ft.",stats:"STR 18  DEX 14  CON 16  INT 6  WIS 12  CHA 8",abilities:"Pack Tactics — Advantage while an ally is within 5 feet.\nRending Bite — +6 to hit, 2d10 + 4 piercing.",spells:"No spells",slots:[0,0,0,0,0]},
  ],
  sessions:[{id:"n1",title:"Session 12 — The Ashen Crossing",date:"2026-09-28",body:"Open on the bridge at dawn. The green scale reacts to the old ward-stone.\n\nRemember: Captain Vael knows more than she admitted.",done:false}],
  story:[
    {id:"s1",title:"The order is destroyed",chapter:"Prologue",details:"Lamfurion returns to find the sanctuary burned and a single green scale among the ashes.",status:"happened"},
    {id:"s2",title:"Trace the ward-stone",chapter:"Chapter II",details:"The party must reach the Ashen Crossing before the cult removes the stone.",status:"active"},
    {id:"s3",title:"Reveal the Verdant Oath",chapter:"Chapter III",details:"The scale belongs to an ancient guardian bound beneath Neverwinter.",status:"planned"},
  ]
};

export default function Home(){
  const [data,setData]=useState<CampaignState>(seed); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [currentId,setCurrentId]=useState(""); const [loaded,setLoaded]=useState(false); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState("Loading…"); const [mobile,setMobile]=useState(false); const [authRequired,setAuthRequired]=useState(false); const [user,setUser]=useState<{email:string;displayName:string}|null>(null); const [shareOpen,setShareOpen]=useState(false); const [shareEmail,setShareEmail]=useState(""); const [shareRole,setShareRole]=useState<"viewer"|"editor">("editor"); const timer=useRef<ReturnType<typeof setTimeout>|null>(null); const fileInput=useRef<HTMLInputElement|null>(null);
  const current=campaigns.find(c=>c.id===currentId); const canEdit=current?.role!=="viewer";
  const ordered=useMemo(()=>[...data.combatants].sort((a,b)=>b.initiative-a.initiative),[data.combatants]);
  useEffect(()=>{void initialise()},[]);
  useEffect(()=>{if(!loaded||!currentId||!canEdit)return;if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>save(data),700);return()=>{if(timer.current)clearTimeout(timer.current)}},[data,loaded,currentId,canEdit]);
  useEffect(()=>{if(!loaded||authRequired)return;const poll=setInterval(()=>void refresh(false),5000);return()=>clearInterval(poll)},[loaded,authRequired,currentId,campaigns]);
  useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"advance_combat_turn",title:"Advance combat turn",description:"Move the visible initiative tracker to the next combatant and advance the round when needed.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{advance();return {advanced:true}}},{signal:lifecycle.signal}));return()=>lifecycle.abort()},[data.turn,ordered.length]);
  async function initialise(){const cached=await readCachedCampaigns<CampaignState>().catch(()=>[]);if(cached.length){setCampaigns(cached);setCurrentId(cached[0].id);setData(normalise(cached[0].payload))}await refresh(true)}
  function normalise(value:CampaignState){return {...value,combatants:(value.combatants??[]).map((c:Combatant & {kind?:string;condition?:string})=>({...c,kind:c.kind==="hero"?"player":c.kind||"monster",conditions:c.conditions??(c.condition?[c.condition]:[])})),players:value.players??[],monsters:value.monsters??[],sessions:value.sessions??[],story:value.story??[]}}
  async function refresh(initial:boolean){try{const r=await fetch("/api/campaigns",{cache:"no-store"});if(r.status===401){setAuthRequired(true);setLoaded(true);return}if(!r.ok)throw new Error();const response=await r.json() as {user:{email:string;displayName:string};campaigns:Campaign[]};setUser(response.user);setAuthRequired(false);let incoming=response.campaigns;if(!incoming.length){const created=await createRemote(seed);incoming=[created]}for(const campaign of incoming)await cacheCampaign(campaign);setCampaigns(incoming);const selected=incoming.find(c=>c.id===(currentId||incoming[0]?.id))??incoming[0];if(selected&&(initial||!currentId||new Date(selected.updatedAt)>new Date(campaigns.find(c=>c.id===selected.id)?.updatedAt??0))){setCurrentId(selected.id);setData(normalise(selected.payload))}setSaved("Synced");setLoaded(true)}catch{setLoaded(true);setSaved("Offline — saved locally");if(initial)toast.info("Working from this device's cached campaigns")}}
  async function createRemote(payload:CampaignState,name=payload.campaignName){const r=await fetch("/api/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,payload})});if(!r.ok)throw new Error("Campaign could not be created");return await r.json() as Campaign}
  async function save(next=data){if(!current)return;const now=new Date().toISOString();const local={...current,name:next.campaignName,payload:next,updatedAt:now};setCampaigns(list=>list.map(c=>c.id===current.id?local:c));await cacheCampaign(local);if(authRequired){setSaved("Saved on this device");return}setSaving(true);try{const r=await fetch("/api/campaigns",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({id:current.id,name:next.campaignName,payload:next})});if(!r.ok)throw new Error();const x=await r.json();const synced={...local,updatedAt:x.updatedAt};setCampaigns(list=>list.map(c=>c.id===current.id?synced:c));await cacheCampaign(synced);setSaved("Synced just now")}catch{setSaved("Offline — saved locally")}finally{setSaving(false)}}
  async function addCampaign(){try{const payload={...seed,campaignName:"New campaign",round:1,turn:0,combatants:[],players:[],sessions:[],story:[]};const created=await createRemote(payload);await cacheCampaign(created);setCampaigns(list=>[created,...list]);setCurrentId(created.id);setData(payload);toast.success("Campaign created")}catch{toast.error("Campaign could not be created")}}
  function selectCampaign(id:string){const selected=campaigns.find(c=>c.id===id);if(selected){setCurrentId(id);setData(normalise(selected.payload))}}
  async function deleteCampaign(){if(!current||current.role!=="owner"||!confirm(`Delete "${current.name}"? This cannot be undone.`))return;const r=await fetch(`/api/campaigns?id=${encodeURIComponent(current.id)}`,{method:"DELETE"});if(!r.ok){toast.error("Campaign could not be deleted");return}await removeCachedCampaign(current.id);const remaining=campaigns.filter(c=>c.id!==current.id);setCampaigns(remaining);if(remaining[0]){setCurrentId(remaining[0].id);setData(remaining[0].payload)}else await addCampaign()}
  function exportCampaign(){if(!current)return;const blob=new Blob([JSON.stringify({format:"dm-command-table",version:1,name:current.name,payload:data},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${current.name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()||"campaign"}.json`;a.click();URL.revokeObjectURL(url)}
  async function importCampaign(file:File){try{const parsed=JSON.parse(await file.text()) as {name?:string;payload?:CampaignState};if(!parsed.payload?.campaignName)throw new Error();const created=await createRemote(normalise(parsed.payload),parsed.name??parsed.payload.campaignName);await cacheCampaign(created);setCampaigns(list=>[created,...list]);setCurrentId(created.id);setData(created.payload);toast.success("Campaign imported")}catch{toast.error("That file is not a valid DM Command Table campaign")}}
  async function share(){if(!current||!shareEmail.trim())return;const r=await fetch("/api/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"share",id:current.id,email:shareEmail,role:shareRole})});if(!r.ok){toast.error("Invitation could not be saved");return}setCampaigns(list=>list.map(c=>c.id===current.id?{...c,shared:true}:c));setShareEmail("");setShareOpen(false);toast.success("Campaign access granted")}
  function patch<T extends keyof CampaignState>(key:T,value:CampaignState[T]){if(canEdit)setData(d=>({...d,[key]:value}))}
  function updateCombat(id:string,part:Partial<Combatant>){if(canEdit)patch("combatants",data.combatants.map(c=>c.id===id?{...c,...part}:c))}
  function advance(){
    if(!canEdit||!ordered.length)return;
    let next=-1;
    for(let step=1;step<=ordered.length;step++){
      const candidate=(data.turn+step)%ordered.length;
      if(ordered[candidate].hp>0){next=candidate;break}
    }
    if(next<0)return;
    setData(d=>({...d,turn:next,round:next<=d.turn?d.round+1:d.round}))
  }
  if(authRequired)return <main className="grid min-h-screen place-items-center bg-[#0b0d12] p-6 text-[#f5f0e5]"><div className="max-w-md rounded-2xl border border-amber-300/20 bg-[#12161e] p-8 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-amber-300/10 text-amber-300"><Swords/></span><h1 className="mt-5 font-serif text-3xl">DM Command Table</h1><p className="mt-3 leading-relaxed text-stone-400">Sign in to sync campaigns between devices and collaborate with your party. Your browser cache remains available offline.</p><a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="mt-6 inline-flex h-10 items-center rounded-md bg-amber-300 px-5 font-medium text-black hover:bg-amber-200">Sign in with ChatGPT</a></div></main>;
  return <main className="min-h-screen bg-[#0b0d12] text-[#f5f0e5]">
    <Toaster theme="dark" position="bottom-right" />
    <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/10 bg-[#0b0d12]/95 px-4 backdrop-blur md:px-7">
      <div className="flex min-w-0 items-center gap-3"><button className="md:hidden" onClick={()=>setMobile(!mobile)} aria-label="Open navigation"><Menu/></button><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-amber-400/30 bg-amber-300/10 text-amber-300"><Swords size={20}/></span><div className="min-w-0"><p className="font-serif text-lg font-semibold leading-none">DM Command Table</p><select aria-label="Current campaign" className="mt-1 max-w-56 bg-transparent text-xs text-stone-400 outline-none" value={currentId} onChange={e=>selectCampaign(e.target.value)}>{campaigns.map(c=><option className="bg-[#12161e]" key={c.id} value={c.id}>{c.name}{c.role!=="owner"?` · ${c.role}`:""}</option>)}</select></div></div>
      <div className="flex items-center gap-2 text-xs text-stone-400"><span className="hidden lg:inline">{saving?"Saving…":saved}</span><Button size="sm" variant="outline" className="hidden border-white/15 bg-transparent hover:bg-white/5 sm:inline-flex" onClick={addCampaign}><Plus/> Campaign</Button><Button size="icon" variant="outline" className="border-white/15 bg-transparent" onClick={exportCampaign} title="Export campaign"><Download/></Button><Button size="icon" variant="outline" className="border-white/15 bg-transparent" onClick={()=>fileInput.current?.click()} title="Import campaign"><Upload/></Button>{current?.role==="owner"&&<Button size="icon" variant="outline" className="border-white/15 bg-transparent" onClick={()=>setShareOpen(true)} title="Share campaign"><Share2/></Button>}<Button size="sm" variant="outline" className="border-white/15 bg-transparent hover:bg-white/5" disabled={!canEdit} onClick={()=>save()}><Save size={15}/> Save</Button><a href="/signout-with-chatgpt?return_to=%2F" target="_top" title={user?.email}><LogOut size={17}/></a><input ref={fileInput} type="file" accept="application/json,.json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importCampaign(f);e.currentTarget.value=""}}/></div>
    </header>
    <Tabs defaultValue="combat" orientation="vertical" className="flex min-h-[calc(100vh-4rem)] gap-0">
      <aside className={`${mobile?"fixed inset-x-0 top-16 z-20 flex":"hidden"} max-h-[calc(100vh-4rem)] w-full flex-col overflow-y-auto border-b border-white/10 bg-[#11141b] p-3 md:static md:flex md:min-h-[calc(100vh-4rem)] md:w-56 md:shrink-0 md:border-b-0 md:border-r`}>
        <p className="mb-2 px-3 pt-2 text-[11px] font-semibold uppercase tracking-[.18em] text-amber-300/70">Campaign desk</p>
        <TabsList variant="line" className="h-auto w-full shrink-0 flex-col items-stretch gap-1 bg-transparent p-0">
          <Nav value="combat" icon={<Swords/>}>Combat</Nav><Nav value="bestiary" icon={<Library/>}>Bestiary</Nav><Nav value="campaign" icon={<Users/>}>Campaign</Nav><Nav value="sessions" icon={<Feather/>}>Sessions</Nav><Nav value="story" icon={<ScrollText/>}>Story</Nav>
        </TabsList>
        <div className="mt-auto hidden rounded-xl border border-white/10 bg-black/20 p-3 md:block"><p className="text-xs font-medium text-stone-300">{current?.shared?"Shared campaign":"Private campaign"} · {current?.role??"owner"}</p><p className="mt-1 text-xs leading-relaxed text-stone-500">Saved locally and synced to your account.</p>{current?.role==="owner"&&<button onClick={deleteCampaign} className="mt-3 text-xs text-red-300/70 hover:text-red-300">Delete campaign</button>}</div>
      </aside>
      <section className="min-w-0 flex-1 p-4 md:p-7">
        <TabsContent value="combat"><Combat data={data} ordered={ordered} update={updateCombat} patch={patch} advance={advance}/></TabsContent>
        <TabsContent value="bestiary"><Bestiary data={data} patch={patch}/></TabsContent>
        <TabsContent value="campaign"><CampaignPlayers data={data} patch={patch}/></TabsContent>
        <TabsContent value="sessions"><Sessions data={data} patch={patch}/></TabsContent>
        <TabsContent value="story"><Story data={data} patch={patch}/></TabsContent>
      </section>
    </Tabs>
    <Dialog open={shareOpen} onOpenChange={setShareOpen}><DialogContent className="border-amber-300/20 bg-[#12161e] text-stone-100"><DialogHeader><DialogTitle className="font-serif text-2xl text-amber-100">Share campaign</DialogTitle></DialogHeader><p className="text-sm leading-relaxed text-stone-400">Grant access using the email address connected to the collaborator's ChatGPT account. Pending access activates when they first sign in.</p><label className="text-sm text-stone-300">Email address<Input className="mt-2 border-white/10 bg-black/20" type="email" value={shareEmail} onChange={e=>setShareEmail(e.target.value)} placeholder="player@example.com"/></label><label className="text-sm text-stone-300">Permission<select className="mt-2 h-10 w-full rounded-md border border-white/10 bg-black/25 px-3" value={shareRole} onChange={e=>setShareRole(e.target.value as "viewer"|"editor")}><option value="editor">Editor — can change campaign data</option><option value="viewer">Viewer — read only</option></select></label><Button onClick={share} className="bg-amber-300 text-black hover:bg-amber-200"><Share2/> Grant access</Button></DialogContent></Dialog>
  </main>
}

function Nav({value,icon,children}:{value:string;icon:React.ReactNode;children:React.ReactNode}){return <TabsTrigger value={value} className="h-11 flex-none justify-start gap-3 rounded-lg px-3 py-2 text-stone-400 after:hidden data-[state=active]:bg-amber-300/10 data-[state=active]:text-amber-200 [&_svg]:size-4">{icon}{children}</TabsTrigger>}
function Title({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-300/70">{eyebrow}</p><h1 className="mt-1 font-serif text-3xl font-semibold tracking-tight md:text-4xl">{title}</h1></div>{action}</div>}

function Combat({data,ordered,update,patch,advance}:{data:CampaignState;ordered:Combatant[];update:(id:string,p:Partial<Combatant>)=>void;patch:<T extends keyof CampaignState>(k:T,v:CampaignState[T])=>void;advance:()=>void}){
 const [selectedId,setSelectedId]=useState(ordered[0]?.id??""); const [newCondition,setNewCondition]=useState(""); const [playerPickerOpen,setPlayerPickerOpen]=useState(false);
 const active=ordered[data.turn]; const selected=ordered.find(c=>c.id===selectedId)??ordered[0]; const monster=data.monsters.find(m=>m.id===selected?.monsterId); const hasStandingCombatant=ordered.some(c=>c.hp>0);
 const add=()=>{const id=uid();patch("combatants",[...data.combatants,{id,name:"New combatant",kind:"monster",initiative:10,hp:10,maxHp:10,ac:10,conditions:[]}]);setSelectedId(id)};
 const addCampaignPlayer=(player:CampaignPlayer)=>{const id=uid();const hp=player.hp??10;patch("combatants",[...data.combatants,{id,name:player.name,kind:"player",initiative:10,hp,maxHp:hp,ac:player.ac??10,conditions:[],campaignPlayerId:player.id}]);setSelectedId(id);setPlayerPickerOpen(false)};
 const colors={monster:{dot:"bg-red-400",border:"border-red-400/45",bg:"bg-red-400/[.07]",text:"text-red-300"},player:{dot:"bg-emerald-400",border:"border-emerald-400/45",bg:"bg-emerald-400/[.07]",text:"text-emerald-300"},npc:{dot:"bg-sky-400",border:"border-sky-400/45",bg:"bg-sky-400/[.07]",text:"text-sky-300"}};
 const addCondition=()=>{const value=newCondition.trim();if(value&&selected&&!selected.conditions.includes(value))update(selected.id,{conditions:[...selected.conditions,value]});setNewCondition("")};
 return <><Title eyebrow="Live encounter" title="The Ashen Crossing" action={<div className="flex flex-wrap justify-end gap-2"><Dialog open={playerPickerOpen} onOpenChange={setPlayerPickerOpen}><DialogTrigger render={<Button className="bg-amber-300 text-black hover:bg-amber-200"/>}><Users/> Add campaign player</DialogTrigger><DialogContent className="border-amber-300/20 bg-[#12161e] text-stone-100"><DialogHeader><DialogTitle className="font-serif text-2xl text-amber-100">Add campaign player</DialogTitle></DialogHeader>{data.players.length?<div className="space-y-2">{data.players.map(player=><div key={player.id} className="flex items-center gap-3 rounded-lg border border-white/10 bg-black/20 p-3"><div className="min-w-0 flex-1"><p className="truncate font-medium text-stone-200">{player.name||"Unnamed player"}</p><p className="mt-1 text-xs text-stone-500">HP {player.hp??"Not set"} · AC {player.ac??"Not set"}</p></div><Button size="sm" onClick={()=>addCampaignPlayer(player)} className="bg-amber-300 text-black hover:bg-amber-200"><Plus/> Add</Button></div>)}</div>:<div className="rounded-lg border border-dashed border-white/10 p-6 text-center text-sm text-stone-500">No saved players yet. Add them from the Campaign menu first.</div>}</DialogContent></Dialog><Button onClick={add} className="bg-amber-300 text-black hover:bg-amber-200"><Plus/> Add combatant</Button></div>}/>
 <div className="mb-5 flex flex-wrap items-center gap-4 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4"><div><p className="text-xs uppercase tracking-wider text-stone-500">Round</p><p className="font-serif text-2xl text-amber-200">{data.round}</p></div><div className="h-9 w-px bg-white/10"/><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-wider text-stone-500">Current turn</p><p className={`truncate font-medium ${active?.hp===0?"text-red-300":""}`}>{active?.name??"No combatants"}{active?.hp===0?" — Down":""}</p></div><Button disabled={!hasStandingCombatant} onClick={advance} className="bg-[#d75b42] hover:bg-[#ec6b50] disabled:bg-stone-700">Next turn <ChevronRight/></Button></div>
 <div className="grid gap-5 xl:grid-cols-[minmax(360px,0.9fr)_minmax(420px,1.1fr)]">
  <section className="space-y-2" aria-label="Initiative tracker">{ordered.map((c,i)=>{const tone=colors[c.kind];const down=c.hp<=0;return <button key={c.id} onClick={()=>setSelectedId(c.id)} className={`grid w-full grid-cols-[44px_1fr_auto] items-center gap-3 rounded-xl border p-3 text-left transition ${down?"border-red-500/50 bg-red-950/20":selected?.id===c.id?`${tone.border} ${tone.bg}`:"border-white/10 bg-[#12161e] hover:border-white/20"} ${selected?.id===c.id&&down?"ring-1 ring-red-400/40":""}`}>
   <span className={`grid h-10 w-10 place-items-center rounded-full bg-black/25 font-serif text-lg ${down?"text-red-300":tone.text}`}>{c.initiative}</span><span className="min-w-0"><span className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${down?"bg-red-500":tone.dot}`}/><span className={`truncate font-medium ${down?"text-stone-400 line-through decoration-red-400/70":""}`}>{c.name}</span>{down&&<Badge className="border border-red-400/30 bg-red-500/15 text-red-200">Down · 0 HP</Badge>}{i===data.turn&&<Badge className="bg-amber-300/15 text-amber-200">Turn</Badge>}</span><span className="mt-1 block truncate text-xs text-stone-500">{c.kind.charAt(0).toUpperCase()+c.kind.slice(1)} · AC {c.ac}{c.conditions.length?` · ${c.conditions.join(", ")}`:""}</span></span><span className="text-right text-xs"><span className={`block ${down?"font-semibold text-red-300":"text-stone-300"}`}>{c.hp}/{c.maxHp} HP</span><Progress value={Math.max(0,c.hp/c.maxHp*100)} className="mt-2 h-1.5 w-20 bg-white/10"/></span>
  </button>})}</section>
  <aside className="rounded-xl border border-white/10 bg-[#12161e] p-5 xl:sticky xl:top-20 xl:self-start">{selected?<>
   <div className="flex items-start gap-3"><div className="min-w-0 flex-1"><label className="group relative block"><span className="sr-only">Combatant name</span><Input className="h-11 border-white/10 bg-black/20 pr-10 font-serif text-xl text-amber-100" value={selected.name} onFocus={e=>e.currentTarget.select()} onChange={e=>update(selected.id,{name:e.target.value})}/><Pencil className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-stone-500"/></label></div><Button size="icon" variant="ghost" className="text-stone-600 hover:text-red-300" onClick={()=>{patch("combatants",data.combatants.filter(x=>x.id!==selected.id));setSelectedId("")}}><Trash2/></Button></div>
   <div className="mt-4 grid grid-cols-3 gap-3"><label className="text-xs text-stone-500">Type<select className="mt-1 h-10 w-full rounded-md border border-white/10 bg-black/25 px-2 font-medium text-stone-200 outline-none transition focus:border-amber-300/50 focus:ring-2 focus:ring-amber-300/10" value={selected.kind} onChange={e=>update(selected.id,{kind:e.target.value as Combatant["kind"]})}><option className="bg-[#12161e] text-stone-200" value="monster">Monster</option><option className="bg-[#12161e] text-stone-200" value="player">Player</option><option className="bg-[#12161e] text-stone-200" value="npc">NPC</option></select></label><label className="text-xs text-stone-500">Initiative<Input className="mt-1 border-white/10 bg-black/20" type="number" value={selected.initiative} onChange={e=>update(selected.id,{initiative:+e.target.value})}/></label><label className="text-xs text-stone-500">Armor class<Input className="mt-1 border-white/10 bg-black/20" type="number" value={selected.ac} onChange={e=>update(selected.id,{ac:+e.target.value})}/></label></div>
   <div className="mt-5"><div className="mb-2 flex justify-between text-sm"><span className="text-stone-400">Hit points</span><span>{selected.hp} / {selected.maxHp}</span></div><Progress value={Math.max(0,selected.hp/selected.maxHp*100)} className="h-2.5 bg-white/10"/><div className="mt-3 flex items-center gap-2"><Button size="icon" variant="outline" className="border-white/10" onClick={()=>update(selected.id,{hp:Math.max(0,selected.hp-1)})}><Minus/></Button><Input className="w-20 border-white/10 bg-black/20 text-center" type="number" value={selected.hp} onChange={e=>update(selected.id,{hp:+e.target.value})}/><span className="text-stone-600">/</span><Input aria-label="Maximum hit points" className="w-20 border-white/10 bg-black/20 text-center" type="number" value={selected.maxHp} onChange={e=>update(selected.id,{maxHp:+e.target.value})}/><Button size="icon" variant="outline" className="border-white/10" onClick={()=>update(selected.id,{hp:Math.min(selected.maxHp,selected.hp+1)})}><Plus/></Button></div></div>
   <section className="mt-6 border-t border-white/10 pt-5"><h3 className="font-serif text-lg text-amber-200">Status conditions</h3><div className="mt-3 flex flex-wrap gap-2">{selected.conditions.length?selected.conditions.map(condition=><Badge key={condition} className="gap-1 bg-violet-400/15 py-1.5 text-violet-200">{condition}<button aria-label={`Remove ${condition}`} onClick={()=>update(selected.id,{conditions:selected.conditions.filter(x=>x!==condition)})}><X size={13}/></button></Badge>):<span className="text-sm text-stone-600">No active conditions</span>}</div><div className="mt-3 flex gap-2"><Input list="condition-options" placeholder="Add a condition…" className="border-white/10 bg-black/20" value={newCondition} onChange={e=>setNewCondition(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addCondition()}}/><datalist id="condition-options">{["Blinded","Charmed","Deafened","Frightened","Grappled","Incapacitated","Invisible","Paralyzed","Petrified","Poisoned","Prone","Restrained","Stunned","Unconscious","Concentrating"].map(x=><option key={x} value={x}/>)}</datalist><Button onClick={addCondition} variant="outline" className="border-white/10"><Plus/> Add</Button></div></section>
   {monster?<div className="mt-6 border-t border-white/10 pt-5"><div className="mb-3 flex items-center justify-between"><div><h3 className="font-serif text-2xl text-amber-100">{monster.name}</h3><p className="text-sm italic text-stone-500">{monster.type} · CR {monster.cr}</p></div></div><div className="grid grid-cols-3 gap-2"><Stat label="Armor class" value={monster.ac}/><Stat label="Hit points" value={monster.hp}/><Stat label="Speed" value={monster.speed}/></div><Section title="Ability scores">{monster.stats}</Section><Section title="Actions & traits">{monster.abilities}</Section><Section title="Spellcasting">{monster.spells}<div className="mt-3 flex flex-wrap gap-2">{monster.slots.map((n,i)=><span key={i} className="rounded-md border border-violet-300/20 bg-violet-300/5 px-2 py-1 text-xs text-violet-200">Level {i+1}: {n}</span>)}</div></Section></div>:<div className="mt-6 rounded-lg border border-dashed border-white/10 p-6 text-center text-sm text-stone-500">No bestiary stat block linked to this combatant.</div>}
  </>:<div className="grid min-h-72 place-items-center text-stone-500">Select a combatant to view details.</div>}</aside>
 </div></>
}

function Bestiary({data,patch}:{data:CampaignState;patch:<T extends keyof CampaignState>(k:T,v:CampaignState[T])=>void}){const add=()=>patch("monsters",[...data.monsters,{id:uid(),name:"Untitled creature",type:"Medium creature",cr:"1",ac:12,hp:20,speed:"30 ft.",stats:"STR 10  DEX 10  CON 10  INT 10  WIS 10  CHA 10",abilities:"Add actions and abilities here.",spells:"No spells",slots:[0,0,0,0,0]}]);return <><Title eyebrow="Creature library" title="Bestiary" action={<Button onClick={add} className="bg-amber-300 text-black hover:bg-amber-200"><Plus/> New monster</Button>}/><div className="grid gap-4 lg:grid-cols-2">{data.monsters.map(m=><div key={m.id} className="rounded-xl border border-white/10 bg-[#12161e] p-5"><div className="flex items-start justify-between"><div><h2 className="font-serif text-2xl text-amber-100">{m.name}</h2><p className="mt-1 text-sm italic text-stone-500">{m.type} · CR {m.cr}</p></div><MonsterDialog monster={m} trigger={<Button size="sm" variant="outline" className="border-white/10">Open</Button>}/></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Stat label="Armor" value={m.ac}/><Stat label="Hit points" value={m.hp}/><Stat label="Speed" value={m.speed}/></div><p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-stone-400">{m.abilities.split("\n")[0]}</p></div>)}</div></>}
function Stat({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-lg bg-black/25 p-2"><p className="text-[10px] uppercase tracking-wider text-stone-500">{label}</p><p className="mt-1 text-sm font-semibold text-stone-200">{value}</p></div>}
function MonsterDialog({monster,trigger}:{monster?:Monster;trigger:React.ReactNode}){if(!monster)return <span className="text-xs text-stone-600">No stat block</span>;return <Dialog><DialogTrigger render={<span className="contents"/>}>{trigger}</DialogTrigger><DialogContent className="max-h-[88vh] overflow-y-auto border-amber-300/20 bg-[#12161e] text-stone-100 sm:max-w-2xl"><DialogHeader><DialogTitle className="font-serif text-3xl text-amber-100">{monster.name}</DialogTitle><p className="text-sm italic text-stone-500">{monster.type} · CR {monster.cr}</p></DialogHeader><div className="grid grid-cols-3 gap-2"><Stat label="Armor class" value={monster.ac}/><Stat label="Hit points" value={monster.hp}/><Stat label="Speed" value={monster.speed}/></div><Section title="Ability scores">{monster.stats}</Section><Section title="Actions & traits">{monster.abilities}</Section><Section title="Spellcasting">{monster.spells}<div className="mt-3 flex flex-wrap gap-3">{monster.slots.map((n,i)=><span key={i} className="rounded-md border border-violet-300/20 bg-violet-300/5 px-2 py-1 text-xs text-violet-200">Level {i+1}: {n} slots</span>)}</div></Section></DialogContent></Dialog>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-2 border-t border-white/10 pt-4"><h3 className="mb-2 flex items-center gap-2 font-serif text-lg text-amber-200"><CircleDot size={14}/>{title}</h3><div className="whitespace-pre-line text-sm leading-7 text-stone-300">{children}</div></section>}

function CampaignPlayers({data,patch}:{data:CampaignState;patch:<T extends keyof CampaignState>(k:T,v:CampaignState[T])=>void}){
 const update=(id:string,part:Partial<CampaignPlayer>)=>patch("players",data.players.map(player=>player.id===id?{...player,...part}:player));
 const add=()=>patch("players",[...data.players,{id:uid(),name:"New player",hp:null,ac:null}]);
 return <><Title eyebrow="Reusable party roster" title="Campaign players" action={<Button onClick={add} className="bg-amber-300 text-black hover:bg-amber-200"><Plus/> Add player</Button>}/><p className="mb-5 max-w-2xl text-sm leading-relaxed text-stone-400">Save the party once, then add these players to any encounter from the Combat menu. HP and armor class are optional; unset values default to 10 when added to combat.</p>{data.players.length?<div className="grid gap-4 lg:grid-cols-2">{data.players.map(player=><article key={player.id} className="rounded-xl border border-white/10 bg-[#12161e] p-5"><div className="flex items-start gap-3"><label className="min-w-0 flex-1 text-xs text-stone-500">Player name<Input className="mt-1 border-white/10 bg-black/20 font-serif text-lg text-amber-100" value={player.name} onChange={e=>update(player.id,{name:e.target.value})}/></label><Button size="icon" variant="ghost" className="mt-5 text-stone-600 hover:text-red-300" onClick={()=>patch("players",data.players.filter(x=>x.id!==player.id))} aria-label={`Delete ${player.name}`}><Trash2/></Button></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs text-stone-500">Hit points (optional)<Input min="0" className="mt-1 border-white/10 bg-black/20" type="number" placeholder="Not set" value={player.hp??""} onChange={e=>update(player.id,{hp:e.target.value===""?null:Math.max(0,+e.target.value)})}/></label><label className="text-xs text-stone-500">Armor class (optional)<Input min="0" className="mt-1 border-white/10 bg-black/20" type="number" placeholder="Not set" value={player.ac??""} onChange={e=>update(player.id,{ac:e.target.value===""?null:Math.max(0,+e.target.value)})}/></label></div></article>)}</div>:<div className="rounded-xl border border-dashed border-white/10 bg-[#12161e]/50 p-10 text-center"><Users className="mx-auto text-stone-600"/><h2 className="mt-3 font-serif text-xl text-stone-300">No campaign players yet</h2><p className="mt-2 text-sm text-stone-500">Add the party here to reuse their details across encounters.</p></div>}</>
}

function Sessions({data,patch}:{data:CampaignState;patch:<T extends keyof CampaignState>(k:T,v:CampaignState[T])=>void}){const update=(id:string,p:Partial<SessionNote>)=>patch("sessions",data.sessions.map(n=>n.id===id?{...n,...p}:n));return <><Title eyebrow="Preparation & recap" title="Session notes" action={<Button onClick={()=>patch("sessions",[{id:uid(),title:"New session",date:new Date().toISOString().slice(0,10),body:"",done:false},...data.sessions])} className="bg-amber-300 text-black hover:bg-amber-200"><Plus/> New note</Button>}/><div className="grid gap-4 xl:grid-cols-2">{data.sessions.map(n=><article key={n.id} className={`rounded-xl border p-5 ${n.done?"border-emerald-300/15 bg-emerald-300/[.03]":"border-white/10 bg-[#12161e]"}`}><div className="flex gap-3"><button onClick={()=>update(n.id,{done:!n.done})} className={`mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full border ${n.done?"border-emerald-300 bg-emerald-300 text-black":"border-white/20"}`} aria-label="Mark session complete">{n.done&&<Check size={15}/>}</button><div className="min-w-0 flex-1"><Input className="border-0 bg-transparent px-0 font-serif text-xl text-amber-100" value={n.title} onChange={e=>update(n.id,{title:e.target.value})}/><Input type="date" className="mt-1 h-8 w-40 border-white/10 bg-black/20 text-xs" value={n.date} onChange={e=>update(n.id,{date:e.target.value})}/></div><Button size="icon" variant="ghost" className="text-stone-600" onClick={()=>patch("sessions",data.sessions.filter(x=>x.id!==n.id))}><Trash2/></Button></div><Textarea className="mt-4 min-h-52 resize-y border-white/10 bg-black/20 leading-7" placeholder="Scenes, NPC motivations, clues, treasure, reminders…" value={n.body} onChange={e=>update(n.id,{body:e.target.value})}/></article>)}</div></>}

function Story({data,patch}:{data:CampaignState;patch:<T extends keyof CampaignState>(k:T,v:CampaignState[T])=>void}){const update=(id:string,p:Partial<StoryBeat>)=>patch("story",data.story.map(s=>s.id===id?{...s,...p}:s));return <><Title eyebrow="Campaign arc" title="Storyline" action={<Button onClick={()=>patch("story",[...data.story,{id:uid(),title:"New story beat",chapter:"Unsorted",details:"",status:"planned"}])} className="bg-amber-300 text-black hover:bg-amber-200"><Plus/> Add story beat</Button>}/><div className="relative space-y-4 before:absolute before:bottom-6 before:left-[19px] before:top-6 before:w-px before:bg-white/10">{data.story.map((s,i)=><article key={s.id} className="relative grid grid-cols-[40px_1fr] gap-4"><div className={`z-10 mt-5 grid h-10 w-10 place-items-center rounded-full border ${s.status==="happened"?"border-emerald-300/40 bg-emerald-300/15 text-emerald-300":s.status==="active"?"border-amber-300/50 bg-amber-300/15 text-amber-200":"border-white/15 bg-[#12161e] text-stone-600"}`}>{s.status==="happened"?<Check size={18}/>:i+1}</div><div className="rounded-xl border border-white/10 bg-[#12161e] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><Input className="h-auto border-0 bg-transparent p-0 font-serif text-xl text-amber-100" value={s.title} onChange={e=>update(s.id,{title:e.target.value})}/><Input className="mt-1 h-auto border-0 bg-transparent p-0 text-xs uppercase tracking-wider text-stone-500" value={s.chapter} onChange={e=>update(s.id,{chapter:e.target.value})}/></div><select className="rounded-md border border-white/10 bg-black/30 px-3 py-2 text-sm" value={s.status} onChange={e=>update(s.id,{status:e.target.value as StoryBeat["status"]})}><option value="planned">Planned</option><option value="active">Active now</option><option value="happened">Happened</option></select></div><Textarea className="mt-4 min-h-24 border-white/10 bg-black/20" value={s.details} onChange={e=>update(s.id,{details:e.target.value})}/></div></article>)}</div></>}
