import { z } from "zod";
import { getV6Database } from "@/db/v6-sqlite";
import { rejectCrossOrigin } from "@/server/http/origin";
import { createV6ManagedUser, deleteV6ManagedUser, listV6Users, updateV6ManagedUser } from "@/server/v6/accounts";
import { getV6User, registrationStatus, setRegistrationEnabled } from "@/server/v6/auth";
import { apiError, apiJson, jsonBody } from "@/server/v6/http";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
async function admin() { const database = getV6Database(); const user = await getV6User(database); return { database, user }; }
function state(database: ReturnType<typeof getV6Database>) { return { users: listV6Users(database), registrationEnabled: registrationStatus(database).registrationEnabled }; }
export async function GET() { const { database, user } = await admin(); return !user?.isAdmin ? apiJson({ error: "Administrator access required." }, 403) : apiJson(state(database)); }
export async function POST(request: Request) { const origin = rejectCrossOrigin(request); if (origin) return origin; try { const { database, user } = await admin(); if (!user?.isAdmin) return apiJson({ error: "Administrator access required." }, 403); const input = z.object({ username: z.string(), displayName: z.string(), password: z.string() }).parse(await jsonBody(request)); createV6ManagedUser(database, input); return apiJson(state(database), 201); } catch (error) { return apiError(error); } }
export async function PATCH(request: Request) { const origin = rejectCrossOrigin(request); if (origin) return origin; try { const { database, user } = await admin(); if (!user?.isAdmin) return apiJson({ error: "Administrator access required." }, 403); const input = z.object({ action: z.enum(["update", "set-registration"]), id: z.string().optional(), username: z.string().optional(), displayName: z.string().optional(), password: z.string().optional(), isAdmin: z.boolean().optional(), registrationEnabled: z.boolean().optional() }).parse(await jsonBody(request)); if (input.action === "set-registration") setRegistrationEnabled(database, Boolean(input.registrationEnabled)); else { if (!input.id) throw new Error("A user is required."); updateV6ManagedUser(database, input.id, input, user.userId); } return apiJson(state(database)); } catch (error) { return apiError(error); } }
export async function DELETE(request: Request) { const origin = rejectCrossOrigin(request); if (origin) return origin; try { const { database, user } = await admin(); if (!user?.isAdmin) return apiJson({ error: "Administrator access required." }, 403); deleteV6ManagedUser(database, new URL(request.url).searchParams.get("id") ?? "", user.userId); return apiJson(state(database)); } catch (error) { return apiError(error); } }
