"use client";

import { useEffect, useMemo, useState } from "react";
import { Heart, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { RichTextContent, RichTextEditor, richTextToPlainText } from "@/features/rich-text/rich-text";
import { createV6Monster, deleteV6Monster, listV6Monsters, updateV6Monster, uploadV6Screenshot } from "./api-client";
import { Empty, Section } from "./sessions-screen";
import type { V6Monster } from "./types";
import { V6BestiaryImport } from "./bestiary-import";

export function BestiaryScreen({ campaignId, editable }: { campaignId: string; editable: boolean }) {
  const [monsters, setMonsters] = useState<V6Monster[]>([]);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [editing, setEditing] = useState<V6Monster | null>(null);
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; void listV6Monsters(campaignId).then((items) => { if (live) setMonsters(items); }).catch(report); return () => { live = false; }; }, [campaignId]);
  function report(error: unknown) { toast.error(error instanceof Error ? error.message : "Bestiary update failed."); }
  const visible = useMemo(() => { const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean); return monsters.filter((item) => terms.every((term) => `${item.name} ${item.type} ${item.challengeRating} ${item.source ?? ""} ${richTextToPlainText(item.notes)}`.toLowerCase().includes(term))); }, [monsters, query]);
  const allVisibleSelected = visible.length > 0 && visible.every(({ id }) => selected.has(id));
  const someVisibleSelected = visible.some(({ id }) => selected.has(id));
  async function add() { setBusy(true); try { const item = await createV6Monster(campaignId); setMonsters((all) => [...all, item]); setEditing(item); } catch (error) { report(error); } finally { setBusy(false); } }
  async function save() { if (!editing) return; setBusy(true); try { const saved = await updateV6Monster(campaignId, editing); setMonsters((all) => all.map((item) => item.id === saved.id ? saved : item)); setEditing(saved); toast.success("Monster saved"); } catch (error) { report(error); } finally { setBusy(false); } }
  async function remove(ids: string[]) { if (!ids.length || !window.confirm(`Delete ${ids.length} monster${ids.length === 1 ? "" : "s"}?`)) return; setBusy(true); try { for (const id of ids) await deleteV6Monster(campaignId, id); setMonsters((all) => all.filter(({ id }) => !ids.includes(id))); setSelected(new Set()); if (editing && ids.includes(editing.id)) setEditing(null); } catch (error) { report(error); } finally { setBusy(false); } }
  async function favorite(monster: V6Monster) { try { const saved = await updateV6Monster(campaignId, { ...monster, favorite: !monster.favorite }); setMonsters((all) => all.map((item) => item.id === saved.id ? saved : item)); } catch (error) { report(error); } }
  function nonnegative(value: string) { return Math.max(0, Number(value) || 0); }

  return <><Section title="Bestiary" description="Search and maintain local monster stat blocks." query={query} setQuery={setQuery} actions={<>{editable && selected.size > 0 && <Button variant="outline" onClick={() => remove([...selected])}><Trash2 /> Delete ({selected.size})</Button>}{editable && <V6BestiaryImport campaignId={campaignId} monsters={monsters} complete={setMonsters} />}{editable && <Button onClick={add} disabled={busy} className="bg-amber-300 text-black hover:bg-amber-200"><Plus /> Monster</Button>}</>}>
    <div className="overflow-hidden rounded-xl border border-white/10 bg-[#13161d]"><div className="grid grid-cols-[2.5rem_2.5rem_1.5fr_1fr_5rem_5rem_5rem] items-center gap-3 border-b border-white/10 px-4 py-3 text-xs uppercase tracking-wider text-stone-600"><Checkbox aria-label="Select all visible monsters" title="Select all visible monsters" checked={allVisibleSelected ? true : someVisibleSelected ? "indeterminate" : false} disabled={!editable || visible.length === 0} onCheckedChange={(checked) => setSelected((current) => { const next = new Set(current); for (const { id } of visible) { if (checked) next.add(id); else next.delete(id); } return next; })} /><span /><span>Name</span><span>Type</span><span>CR</span><span>HP</span><span>AC</span></div>{visible.map((monster) => <div key={monster.id} className="grid grid-cols-[2.5rem_2.5rem_1.5fr_1fr_5rem_5rem_5rem] items-center gap-3 border-b border-white/5 px-4 py-3 text-sm last:border-0"><Checkbox checked={selected.has(monster.id)} disabled={!editable} onCheckedChange={(checked) => setSelected((current) => { const next = new Set(current); if (checked) next.add(monster.id); else next.delete(monster.id); return next; })} /><button disabled={!editable} title="Toggle favorite" onClick={() => favorite(monster)} className={monster.favorite ? "text-rose-400" : "text-stone-700"}><Heart className={`size-4 ${monster.favorite ? "fill-current" : ""}`} /></button><button className="truncate text-left font-medium text-amber-200 hover:underline" onClick={() => setEditing(monster)}>{monster.name}</button><span className="truncate text-stone-400">{monster.type || "—"}</span><span>{monster.challengeRating || "—"}</span><span>{monster.hitPoints}</span><span>{monster.armorClass}</span></div>)}</div>
    {!visible.length && <Empty>No monsters match this search.</Empty>}
  </Section>
  <Dialog open={!!editing} onOpenChange={(open) => { if (!open) setEditing(null); }}><DialogContent className="max-h-[90vh] overflow-y-auto border-white/10 bg-[#151820] text-stone-100 sm:max-w-3xl">{editing && <><DialogHeader><DialogTitle className="font-serif text-2xl">{editable ? "Edit monster" : editing.name}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Field label="Name"><Input value={editing.name} disabled={!editable} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></Field><Field label="Creature type"><Input value={editing.type} disabled={!editable} onChange={(event) => setEditing({ ...editing, type: event.target.value })} /></Field></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Field label="Challenge rating"><Input value={editing.challengeRating} disabled={!editable} onChange={(event) => setEditing({ ...editing, challengeRating: event.target.value })} /></Field><Field label="Armor class"><Input type="number" min={0} value={editing.armorClass} disabled={!editable} onChange={(event) => setEditing({ ...editing, armorClass: nonnegative(event.target.value) })} /></Field><Field label="Hit points"><Input type="number" min={0} value={editing.hitPoints} disabled={!editable} onChange={(event) => setEditing({ ...editing, hitPoints: nonnegative(event.target.value) })} /></Field><Field label="Speed"><Input value={editing.speed} disabled={!editable} onChange={(event) => setEditing({ ...editing, speed: event.target.value })} /></Field></div><Field label="Ability scores"><RichArea editable={editable} value={editing.stats} onChange={(stats) => setEditing({ ...editing, stats })} /></Field><Field label="Actions & traits"><RichArea editable={editable} value={editing.abilities} onChange={(abilities) => setEditing({ ...editing, abilities })} /></Field><Field label="Spellcasting"><RichArea editable={editable} value={editing.spells} onChange={(spells) => setEditing({ ...editing, spells })} /></Field><Field label="Notes"><RichArea editable={editable} value={editing.notes} onChange={(notes) => setEditing({ ...editing, notes })} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Source"><Input value={editing.source ?? ""} disabled={!editable} onChange={(event) => setEditing({ ...editing, source: event.target.value || null })} /></Field><Field label="Spell slots (levels 1–9)"><Input value={editing.spellSlots.join(", ")} disabled={!editable} onChange={(event) => setEditing({ ...editing, spellSlots: event.target.value.split(",").map((value) => nonnegative(value.trim())).slice(0, 9) })} /></Field></div>{editable && <div className="flex justify-between"><Button variant="ghost" onClick={() => remove([editing.id])}><Trash2 /> Delete</Button><Button onClick={save} disabled={busy}><Save /> Save</Button></div>}</>}</DialogContent></Dialog>
  </>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs text-stone-500">{label}<div className="mt-1">{children}</div></label>; }
function RichArea({ editable, value, onChange }: { editable: boolean; value: string; onChange: (value: string) => void }) { return editable ? <RichTextEditor value={value} onChange={onChange} onPasteImage={uploadV6Screenshot} className="min-h-28" /> : <RichTextContent value={value} />; }
