"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronRight, Plus, RotateCcw, Save, Trash2, Undo2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ConditionIcon, DEFAULT_CONDITIONS } from "@/features/combat/condition-icons";
import { getV6Combat, listV6Monsters, listV6Players, saveV6Combat, undoV6Combat } from "./api-client";
import type { V6Combat, V6Combatant, V6Monster, V6Player } from "./types";

export function CombatScreen({ campaignId, editable }: { campaignId: string; editable: boolean }) {
  const [combat, setCombat] = useState<V6Combat | null>(null);
  const [players, setPlayers] = useState<V6Player[]>([]);
  const [monsters, setMonsters] = useState<V6Monster[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [picker, setPicker] = useState<"players" | "monsters" | null>(null);
  const [chosen, setChosen] = useState<Set<string>>(new Set());
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; void Promise.all([getV6Combat(campaignId), listV6Players(campaignId), listV6Monsters(campaignId)]).then(([next, campaignPlayers, bestiary]) => { if (live) { setCombat(normalize(next)); setPlayers(campaignPlayers); setMonsters(bestiary); setSelectedId(next.combatants[0]?.id ?? ""); } }).catch(report); return () => { live = false; }; }, [campaignId]);
  function report(error: unknown) { toast.error(error instanceof Error ? error.message : "Combat update failed."); }
  const ordered = useMemo(() => combat ? [...combat.combatants].sort((a, b) => b.initiative - a.initiative || a.sortOrder - b.sortOrder) : [], [combat]);
  const active = ordered[combat?.turn ?? 0];
  const selected = ordered.find(({ id }) => id === selectedId) ?? active ?? ordered[0];
  function patchCombat(values: Partial<V6Combat>) { setCombat((current) => current ? { ...current, ...values } : current); }
  function patchSelected(values: Partial<V6Combatant>) { if (!selected) return; setCombat((current) => current ? { ...current, combatants: current.combatants.map((item) => item.id === selected.id ? { ...item, ...values } : item) } : current); }
  async function persist(next: V6Combat, action: string) { setBusy(true); try { const saved = normalize(await saveV6Combat(campaignId, normalize(next), action)); setCombat(saved); return saved; } catch (error) { report(error); return null; } finally { setBusy(false); } }
  async function save() { if (combat && await persist(combat, "details_updated")) toast.success("Combat saved"); }
  async function nextTurn() {
    if (!combat || !ordered.some(({ hitPoints }) => hitPoints > 0)) return;
    let nextIndex = combat.turn; let wrapped = false;
    for (let step = 1; step <= ordered.length; step++) { const candidate = (combat.turn + step) % ordered.length; if (candidate <= combat.turn) wrapped = true; if (ordered[candidate]?.hitPoints > 0) { nextIndex = candidate; break; } }
    const incoming = ordered[nextIndex];
    const combatants = combat.combatants.map((item) => item.id === incoming.id ? { ...item, conditions: item.conditions.flatMap((condition) => condition.remainingTurns === null ? [condition] : condition.remainingTurns > 1 ? [{ ...condition, remainingTurns: condition.remainingTurns - 1 }] : []) } : item);
    const saved = await persist({ ...combat, combatants, turn: nextIndex, round: combat.round + (wrapped ? 1 : 0) }, "next_turn");
    if (saved) setSelectedId(incoming.id);
  }
  async function doUndo() { setBusy(true); try { const restored = normalize(await undoV6Combat(campaignId)); setCombat(restored); setSelectedId(restored.combatants[restored.turn]?.id ?? restored.combatants[0]?.id ?? ""); toast.success("Last combat change undone"); } catch (error) { report(error); } finally { setBusy(false); } }
  async function resetRounds() { if (combat) await persist({ ...combat, round: 1, turn: Math.max(0, ordered.findIndex(({ hitPoints }) => hitPoints > 0)) }, "rounds_reset"); }
  async function clear(kind?: "monster") { if (!combat || !window.confirm(kind ? "Remove all monsters? Players and NPCs will remain." : "Clear every combatant?")) return; const combatants = kind ? combat.combatants.filter((item) => item.kind !== kind) : []; const saved = await persist({ ...combat, combatants, round: 1, turn: 0 }, kind ? "monsters_cleared" : "combat_cleared"); if (saved) setSelectedId(saved.combatants[0]?.id ?? ""); }
  async function removeSelected() { if (!combat || !selected) return; const next = combat.combatants.filter(({ id }) => id !== selected.id); const saved = await persist({ ...combat, combatants: next, turn: 0 }, "combatant_removed"); if (saved) setSelectedId(saved.combatants[0]?.id ?? ""); }
  function addNpc() { if (!combat) return; const item: V6Combatant = { id: crypto.randomUUID(), playerId: null, monsterId: null, name: "New NPC", displayNumber: null, kind: "npc", initiative: 10, hitPoints: 10, maximumHitPoints: 10, armorClass: 10, sortOrder: combat.combatants.length, conditions: [], revision: 1 }; setCombat({ ...combat, combatants: [...combat.combatants, item] }); setSelectedId(item.id); }
  function addCustomMonster() {
    if (!combat) return;
    const displayNumber = Math.max(0, ...combat.combatants.filter(({ kind, monsterId }) => kind === "monster" && !monsterId).map((item) => item.displayNumber ?? 0)) + 1;
    const item = makeCombatant("New Monster", "monster", combat.combatants.length, 10, 10, null, null, displayNumber);
    setCombat({ ...combat, combatants: [...combat.combatants, item] });
    setSelectedId(item.id);
  }
  function addChosen() { if (!combat || !picker) return; const additions: V6Combatant[] = [];
    if (picker === "players") for (const player of players.filter(({ id }) => chosen.has(id) && !combat.combatants.some((item) => item.playerId === id))) { const hp = player.hitPoints ?? 10; additions.push(makeCombatant(player.name, "player", combat.combatants.length + additions.length, hp, player.armorClass ?? 10, player.id, null, null)); }
    if (picker === "monsters") for (const monster of monsters.filter(({ id }) => chosen.has(id))) { const numbers = [...combat.combatants, ...additions].filter((item) => item.monsterId === monster.id).map(({ displayNumber }) => displayNumber ?? 0); additions.push(makeCombatant(monster.name, "monster", combat.combatants.length + additions.length, monster.hitPoints, monster.armorClass, null, monster.id, Math.max(0, ...numbers) + 1)); }
    if (additions.length) { setCombat({ ...combat, combatants: [...combat.combatants, ...additions] }); setSelectedId(additions.at(-1)?.id ?? ""); }
    setPicker(null); setChosen(new Set()); setQuery("");
  }

  if (!combat) return <div className="grid min-h-96 place-items-center text-stone-500">Loading combat tracker…</div>;
  return <div className="mx-auto w-full max-w-[1500px] space-y-5"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">Live encounter</p><Input className="mt-2 h-11 max-w-md font-serif text-2xl" value={combat.name} disabled={!editable} onChange={(event) => patchCombat({ name: event.target.value })} /></div>{editable && <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setPicker("players")}>Add players</Button><Button variant="outline" onClick={() => setPicker("monsters")}>Add bestiary monsters</Button><Button variant="outline" onClick={addCustomMonster}><Plus /> Custom monster</Button><Button variant="outline" onClick={addNpc}><Plus /> NPC</Button><Button onClick={save} disabled={busy}><Save /> Save</Button></div>}</header>
    <div className="flex flex-wrap items-center gap-4 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4"><div><p className="text-xs uppercase text-stone-500">Round</p><p className="font-serif text-2xl text-amber-200">{combat.round}</p></div><div className="h-10 w-px bg-white/10" /><div className="min-w-0 flex-1"><p className="text-xs uppercase text-stone-500">Current turn</p><p className="truncate">{active ? displayName(active) : "No combatants"}</p></div>{editable && <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={doUndo} disabled={busy}><Undo2 /> Undo</Button><Button variant="outline" onClick={resetRounds}><RotateCcw /> Reset rounds</Button><Button variant="outline" onClick={() => clear("monster")}>Clear monsters</Button><Button variant="outline" onClick={() => clear()}>Clear combat</Button><Button onClick={nextTurn} className="bg-[#d75b42] hover:bg-[#ec6b50]">Next turn <ChevronRight /></Button></div>}</div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,3fr)_minmax(0,7fr)]"><div className="overflow-hidden rounded-xl border border-white/10 bg-[#13161d]">{ordered.map((item, index) => <button key={item.id} className={`relative flex w-full items-center gap-3 border-b border-white/5 p-3 text-left last:border-0 ${combatantKindBackground(item.kind)} ${selected?.id === item.id ? "brightness-125" : "hover:brightness-110"} ${index === combat.turn ? "z-10 outline outline-2 -outline-offset-2 outline-amber-300" : ""}`} onClick={() => setSelectedId(item.id)}><span className={`grid size-8 place-items-center rounded font-mono text-sm ${combatantKindBadge(item.kind)}`}>{item.initiative}</span><span className="min-w-0 flex-1"><span className={`block truncate ${item.hitPoints <= 0 ? "text-red-300 line-through" : ""}`}>{displayName(item)}</span><span className={`text-xs capitalize ${combatantKindText(item.kind)}`}>{item.kind} · {item.hitPoints}/{item.maximumHitPoints} HP</span></span>{item.conditions.length > 0 && <span className="flex text-violet-300" title={item.conditions.map(({ name }) => name).join(", ")}><ConditionIcon name={item.conditions[0].name} />{item.conditions.length > 1 && <small>+{item.conditions.length - 1}</small>}</span>}</button>)}</div><CombatantEditor combatant={selected} monster={monsters.find(({ id }) => id === selected?.monsterId)} editable={editable} update={patchSelected} remove={removeSelected} /></div>
    <Picker open={!!picker} kind={picker} players={players} monsters={monsters} existingPlayerIds={new Set(combat.combatants.flatMap(({ playerId }) => playerId ? [playerId] : []))} chosen={chosen} setChosen={setChosen} query={query} setQuery={setQuery} close={() => { setPicker(null); setChosen(new Set()); }} add={addChosen} />
  </div>;
}

function CombatantEditor({ combatant, monster, editable, update, remove }: { combatant?: V6Combatant; monster?: V6Monster; editable: boolean; update: (part: Partial<V6Combatant>) => void; remove: () => void }) {
  const [condition, setCondition] = useState("Poisoned"); const [duration, setDuration] = useState("");
  if (!combatant) return <div className="rounded-xl border border-dashed border-white/10 p-12 text-center text-stone-600">Add a combatant to begin.</div>;
  const current = combatant;
  function addCondition() { const name = condition.trim(); if (!name) return; update({ conditions: [...current.conditions, { id: crypto.randomUUID(), name, remainingTurns: duration ? Math.max(1, Number(duration)) : null }] }); setDuration(""); }
  return <div className="rounded-xl border border-white/10 bg-[#13161d] p-5"><div className="grid gap-3 sm:grid-cols-[1fr_7rem_7rem_7rem]"><Input value={combatant.name} disabled={!editable} onChange={(event) => update({ name: event.target.value })} /><Metric label="Initiative" value={combatant.initiative} disabled={!editable} change={(initiative) => update({ initiative })} /><Metric label="HP" value={combatant.hitPoints} disabled={!editable} change={(hitPoints) => update({ hitPoints })} /><Metric label="Max HP" value={combatant.maximumHitPoints} disabled={!editable} change={(maximumHitPoints) => update({ maximumHitPoints })} /></div><div className="mt-3 grid gap-3 sm:grid-cols-[7rem_10rem_1fr]"><Metric label="Armor class" value={combatant.armorClass} disabled={!editable} change={(armorClass) => update({ armorClass })} /><label className="text-xs text-stone-500">Type<select className="mt-1 h-9 w-full rounded-md border border-white/10 bg-[#191d27] px-2 text-sm text-stone-200" value={combatant.kind} disabled={!editable || !!combatant.playerId} onChange={(event) => update({ kind: event.target.value as V6Combatant["kind"] })}><option value="player">Player</option><option value="monster">Monster</option><option value="npc">NPC</option></select></label></div>
    {monster && <div className="mt-5 rounded-lg border border-white/10 bg-black/20 p-4"><p className="font-serif text-xl text-amber-100">{monster.name}</p><p className="text-xs text-stone-500">{monster.type} · CR {monster.challengeRating} · Speed {monster.speed}</p></div>}
    <div className="mt-5"><p className="text-xs font-medium uppercase tracking-wider text-stone-500">Status conditions</p><div className="mt-2 flex flex-wrap gap-2">{combatant.conditions.map((entry) => <button key={entry.id} disabled={!editable} onClick={() => update({ conditions: combatant.conditions.filter(({ id }) => id !== entry.id) })} className="flex items-center gap-1.5 rounded-full bg-violet-400/15 px-3 py-1.5 text-xs text-violet-200"><ConditionIcon name={entry.name} />{entry.name}{entry.remainingTurns !== null && ` · ${entry.remainingTurns}`}</button>)}</div>{editable && <div className="mt-3 flex flex-wrap gap-2"><Input list="v6-conditions" className="max-w-52" value={condition} onChange={(event) => setCondition(event.target.value)} /><datalist id="v6-conditions">{DEFAULT_CONDITIONS.map((name) => <option key={name} value={name} />)}</datalist><Input className="w-28" type="number" min={1} placeholder="Turns" value={duration} onChange={(event) => setDuration(event.target.value)} /><Button variant="outline" onClick={addCondition}><Plus /> Condition</Button></div>}</div>{editable && <div className="mt-6 flex justify-end"><Button variant="ghost" onClick={remove}><Trash2 /> Remove combatant</Button></div>}</div>;
}

function Picker({ open, kind, players, monsters, existingPlayerIds, chosen, setChosen, query, setQuery, close, add }: { open: boolean; kind: "players" | "monsters" | null; players: V6Player[]; monsters: V6Monster[]; existingPlayerIds: Set<string>; chosen: Set<string>; setChosen: React.Dispatch<React.SetStateAction<Set<string>>>; query: string; setQuery: (value: string) => void; close: () => void; add: () => void }) { const entries = kind === "players" ? players.filter(({ id }) => !existingPlayerIds.has(id)) : monsters; return <Dialog open={open} onOpenChange={(value) => { if (!value) close(); }}><DialogContent className="border-white/10 bg-[#151820] text-stone-100"><DialogHeader><DialogTitle>Add campaign {kind}</DialogTitle></DialogHeader><Input type="search" placeholder="Search…" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="max-h-72 space-y-1 overflow-y-auto">{entries.filter((entry) => entry.name.toLowerCase().includes(query.toLowerCase())).map((entry) => <label key={entry.id} className="flex cursor-pointer gap-3 rounded p-2 hover:bg-white/5"><Checkbox checked={chosen.has(entry.id)} onCheckedChange={(checked) => setChosen((current) => { const next = new Set(current); if (checked) next.add(entry.id); else next.delete(entry.id); return next; })} />{entry.name}</label>)}</div><Button onClick={add} disabled={!chosen.size}>Add selected ({chosen.size})</Button></DialogContent></Dialog>; }
function Metric({ label, value, disabled, change }: { label: string; value: number; disabled: boolean; change: (value: number) => void }) { return <label className="text-xs text-stone-500">{label}<Input className="mt-1" type="number" value={value} disabled={disabled} onChange={(event) => change(Number(event.target.value))} /></label>; }
function makeCombatant(name: string, kind: V6Combatant["kind"], sortOrder: number, hp: number, ac: number, playerId: string | null, monsterId: string | null, displayNumber: number | null): V6Combatant { return { id: crypto.randomUUID(), playerId, monsterId, name, displayNumber, kind, initiative: 10, hitPoints: hp, maximumHitPoints: hp, armorClass: ac, sortOrder, conditions: [], revision: 1 }; }
function displayName(item: V6Combatant) { return `${item.name}${item.kind !== "player" && item.displayNumber ? ` #${item.displayNumber}` : ""}`; }
function combatantKindBackground(kind: V6Combatant["kind"]) { return kind === "player" ? "bg-emerald-500/10" : kind === "monster" ? "bg-red-500/10" : "bg-blue-500/10"; }
function combatantKindBadge(kind: V6Combatant["kind"]) { return kind === "player" ? "bg-emerald-500/20 text-emerald-200" : kind === "monster" ? "bg-red-500/20 text-red-200" : "bg-blue-500/20 text-blue-200"; }
function combatantKindText(kind: V6Combatant["kind"]) { return kind === "player" ? "text-emerald-300" : kind === "monster" ? "text-red-300" : "text-blue-300"; }
function normalize(combat: V6Combat): V6Combat { const combatants = [...combat.combatants].sort((a, b) => b.initiative - a.initiative || a.sortOrder - b.sortOrder).map((item, sortOrder) => ({ ...item, sortOrder })); return { ...combat, combatants, turn: Math.min(combat.turn, Math.max(0, combatants.length - 1)) }; }
