"use client";
import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { searchV6Campaign } from "./api-client";
import type { V6SearchResult, V6Section } from "./types";
export function SearchScreen({ campaignId, navigate }: { campaignId: string; navigate: (section: V6Section, id: string) => void }) { const [query, setQuery] = useState(""); const [results, setResults] = useState<V6SearchResult[]>([]); useEffect(() => { const timer = window.setTimeout(() => { if (!query.trim()) { setResults([]); return; } void searchV6Campaign(campaignId, query).then(setResults); }, 200); return () => clearTimeout(timer); }, [campaignId, query]); return <div className="mx-auto max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Campaign workspace</p><h1 className="mt-1 font-serif text-3xl">Search</h1><div className="relative mt-5"><Search className="absolute left-3 top-3 size-4 text-stone-500" /><Input autoFocus className="h-11 pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search sessions, story, players, and monsters…" /></div><div className="mt-5 space-y-2">{results.map((result) => <button key={`${result.resourceType}:${result.resourceId}`} onClick={() => navigate(resourceSection(result.resourceType), result.resourceId)} className="block w-full rounded-xl border border-white/10 bg-[#13161d] p-4 text-left hover:bg-white/5"><span className="text-xs uppercase tracking-wider text-stone-600">{result.resourceType}</span><p className="mt-1 font-medium text-amber-100">{result.title}</p><p className="mt-1 text-sm text-stone-400">{plainExcerpt(result.excerpt)}</p></button>)}</div></div>; }
function resourceSection(type: string): V6Section { if (type === "session") return "sessions"; if (type === "story") return "story"; if (type === "player") return "players"; return "bestiary"; }
function plainExcerpt(value: string): string { return value.replace(/<\/?mark>/g, "").replace(/<[^>]+>/g, ""); }
